version: '3.1'
services:
  backend:
    build:
        context: ./ms-backend
    restart: always
  db:
    image: postgres:9.6
    volumes: 
      - ./volume/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Senha123! 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
