version: '3'
services:
  backend:
    env_file: .env
    build:
      context: ./ms-backend
    volumes:
      - './ms-backend/dist:/app/dist/'
    ports:
      - "5001:3000"
    depends_on:
      - "db"
    networks:
      - webnet
      
  frontend:
    build:
      context: ./ms-frontend
    volumes:
      - './ms-frontend/src:/app/src'
    ports:
      - "5002:3000"
    depends_on:
      - "backend"
      - "db"
    networks:
      - webnet
  
  db:
    image: mongo:4.2.0-rc2-bionic
    volumes:
      - './data:/data'
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
