version: '3'
services:
  backend:
    build:
      context: ./ms-backend
      dockerfile: Dockerfile-stg
    volumes:
      - './:/app'
    networks:
      - webnet
  frontend:
    build:
      context: ./ms-frontend
      dockerfile: Dockerfile-stg
    volumes:
      - './:/app'
    networks:
      - webnet
  db:
    image: mongo:4.2.0-rc2-bionic
    volumes:
      - './data:/data'
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
