version: '3.1'
services:
  backend:
    build:
        context: ./ms-backend
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Senha123! 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
